name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          java-package: jdk
      - name: Install Node v17
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: yarn install --frozen-lockfile
      - run: yarn test
