name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - run: yarn install --frozen-lockfile
      - run: yarn test
