name: IOS build

on:
  push:
    branches: 
      -  dev

jobs:
  ios-build:
    name: IOS build
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ios
    steps:
      - name: Dump file hierarchy
        run: ls -R
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true
      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      
      - name: Install Pods
        run: pod install --repo-update
    
      - name: Run tests
        run: yarn test

      - name: Build IOS App
        uses: sparkfabrik/ios-build-action@v1.0.0
        with:
          upload-to-testflight: true
          increment-build-number: true
          build-pods: true
          pods-path: 'ios/Podfile'
          configuration: Release
          export-method: app-store
          workspace-path: ios/CiCdGa.xcworkspace
          project-path: ios/CiCdGa.xcodeproj
          apple-key-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          apple-key-content: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          match-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          scheme: CiCdGaProd

